### ISSUE TITLE
"Administratörer" oklart vem? (Journal)

### ISSUE THREAD

**Issue by rhymn** [kaddio/www#2]
"All läsning av journalanteckningar loggas och administratörer kan ta del av vem, när och från vilken ip-adress som en viss klients journal har lästs."

**Comment by ylvena** [comment]
Ändrade så vi inte nämner olika roller, utan bara beskriver funktionen:" All läsning av journalanteckningar loggas och visar vem, när och från vilken ip-adress som en viss klients journal har lästs."
