### ISSUE TITLE
Länk saknar (Journal)

### ISSUE THREAD

**Issue by rhymn** [kaddio/www#3]
Du har tre alternativ när du avslutar ditt abonnemang hos oss. 1. Ladda ner varje klients journal som PDF och själv stå för säker lagring. 2. Få ut all data i det läsbara formatet JSON som gör det möjligt för dig att flytta över alla data till ett annat journalsystem. 3. Sätta ditt konto i Dvala. [Läs mer om det här.](https://help.kaddio.com/help/uppsagning), vilket innebär att du betalar en mindre summa för att vi står för lagringen.

**Comment by ylvena** [comment]
Lyckas inte göra det till en länk. Tog helt enkelt bort länken.
